# Generated by Django 5.2.7 on 2025-10-03 16:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started at"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished at"
                    ),
                ),
                (
                    "new_events_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="New events count"
                    ),
                ),
                (
                    "updated_events_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Updated events count"
                    ),
                ),
                (
                    "is_success",
                    models.BooleanField(default=True, verbose_name="Success"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error message"),
                ),
            ],
            options={
                "verbose_name": "Sync Result",
                "verbose_name_plural": "Sync Results",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Key"),
                ),
                ("value", models.TextField(verbose_name="Value")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Sync Setting",
                "verbose_name_plural": "Sync Settings",
            },
        ),
    ]
