# Generated by Django 5.2.7 on 2025-10-06 19:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=255, verbose_name="Topic")),
                ("payload", models.JSONField(verbose_name="Payload")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent at"),
                ),
            ],
            options={
                "verbose_name": "Outbox Message",
                "verbose_name_plural": "Outbox Messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["sent_at", "created_at"],
                        name="sync_outbox_sent_at_5a36d8_idx",
                    )
                ],
            },
        ),
    ]
