# Generated by Django 5.2.7 on 2025-10-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0002_outboxmessage"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="outboxmessage",
            name="sync_outbox_sent_at_5a36d8_idx",
        ),
        migrations.AddField(
            model_name="outboxmessage",
            name="sent",
            field=models.BooleanField(default=False, verbose_name="Sent"),
        ),
        migrations.AddIndex(
            model_name="outboxmessage",
            index=models.Index(
                fields=["sent", "created_at"], name="sync_outbox_sent_175878_idx"
            ),
        ),
    ]
