# Generated by Django 5.2.7 on 2025-10-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0003_remove_outboxmessage_sync_outbox_sent_at_5a36d8_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncsettings",
            name="sent",
            field=models.BooleanField(default=False, verbose_name="Sent"),
        ),
    ]
