# Generated by Django 5.2.7 on 2025-10-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0004_syncsettings_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxmessage",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Error Message"),
        ),
        migrations.AddField(
            model_name="outboxmessage",
            name="last_retry_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Retry At"
            ),
        ),
        migrations.AddField(
            model_name="outboxmessage",
            name="retry_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Retry Count"),
        ),
        migrations.AddIndex(
            model_name="outboxmessage",
            index=models.Index(
                fields=["retry_count", "created_at"],
                name="sync_outbox_retry_c_829c06_idx",
            ),
        ),
    ]
