# Generated by Django 5.2.7 on 2025-10-03 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placeadmin",
            name="place_ptr",
        ),
        migrations.DeleteModel(
            name="EventAdmin",
        ),
        migrations.DeleteModel(
            name="PlaceAdmin",
        ),
    ]
