# Generated by Django 5.2.7 on 2025-10-08 18:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_remove_placeadmin_place_ptr_delete_eventadmin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=128, verbose_name="Full Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "confirmation_code",
                    models.CharField(max_length=6, verbose_name="Confirmation Code"),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="Confirmed"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "indexes": [
                    models.Index(
                        fields=["event", "email"], name="events_even_event_i_8859f3_idx"
                    ),
                    models.Index(
                        fields=["confirmation_code"],
                        name="events_even_confirm_8efdf8_idx",
                    ),
                ],
                "unique_together": {("event", "email")},
            },
        ),
    ]
